# dist025
docker-f1:
	sudo docker compose -f Fulcrums/docker-compose.yml up f1

# dist025
docker-i1:
	sudo docker compose -f Informantes/MonotonicWrites/docker-compose.yml run monotonicwrites

# dist026
docker-i2:
	sudo docker compose -f Informantes/ReadYourWrites/docker-compose.yml run readyourwrites

# dist026
docker-f2:
	sudo docker compose -f Fulcrums/docker-compose.yml up f2

# dist0027
docker-vanguardia:
	sudo docker compose -f Vanguardia/docker-compose.yml run monotonicreads

# dist027
docker-f3:
	sudo docker compose -f Fulcrums/docker-compose.yml up f3

# dist028
docker-broker:
	sudo docker compose -f Broker/docker-compose.yml up broker