// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/messages.proto

package messages

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	SendInfoState(ctx context.Context, in *InfoState, opts ...grpc.CallOption) (*Ack, error)
	SendInfoID(ctx context.Context, in *InfoID, opts ...grpc.CallOption) (*Ack, error)
	SendRequestNamesByID(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*Names, error)
	SendRequestDeadOrAlive(ctx context.Context, in *State, opts ...grpc.CallOption) (*Names, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) SendInfoState(ctx context.Context, in *InfoState, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/messages.MessageService/SendInfoState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) SendInfoID(ctx context.Context, in *InfoID, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/messages.MessageService/SendInfoID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) SendRequestNamesByID(ctx context.Context, in *Ids, opts ...grpc.CallOption) (*Names, error) {
	out := new(Names)
	err := c.cc.Invoke(ctx, "/messages.MessageService/SendRequestNamesByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) SendRequestDeadOrAlive(ctx context.Context, in *State, opts ...grpc.CallOption) (*Names, error) {
	out := new(Names)
	err := c.cc.Invoke(ctx, "/messages.MessageService/SendRequestDeadOrAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	SendInfoState(context.Context, *InfoState) (*Ack, error)
	SendInfoID(context.Context, *InfoID) (*Ack, error)
	SendRequestNamesByID(context.Context, *Ids) (*Names, error)
	SendRequestDeadOrAlive(context.Context, *State) (*Names, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) SendInfoState(context.Context, *InfoState) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInfoState not implemented")
}
func (UnimplementedMessageServiceServer) SendInfoID(context.Context, *InfoID) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInfoID not implemented")
}
func (UnimplementedMessageServiceServer) SendRequestNamesByID(context.Context, *Ids) (*Names, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequestNamesByID not implemented")
}
func (UnimplementedMessageServiceServer) SendRequestDeadOrAlive(context.Context, *State) (*Names, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequestDeadOrAlive not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_SendInfoState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendInfoState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.MessageService/SendInfoState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendInfoState(ctx, req.(*InfoState))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_SendInfoID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendInfoID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.MessageService/SendInfoID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendInfoID(ctx, req.(*InfoID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_SendRequestNamesByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ids)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendRequestNamesByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.MessageService/SendRequestNamesByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendRequestNamesByID(ctx, req.(*Ids))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_SendRequestDeadOrAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(State)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendRequestDeadOrAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.MessageService/SendRequestDeadOrAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendRequestDeadOrAlive(ctx, req.(*State))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messages.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInfoState",
			Handler:    _MessageService_SendInfoState_Handler,
		},
		{
			MethodName: "SendInfoID",
			Handler:    _MessageService_SendInfoID_Handler,
		},
		{
			MethodName: "SendRequestNamesByID",
			Handler:    _MessageService_SendRequestNamesByID_Handler,
		},
		{
			MethodName: "SendRequestDeadOrAlive",
			Handler:    _MessageService_SendRequestDeadOrAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/messages.proto",
}
